### ISSUE TITLE
terramap 0.6 and the 2 fix versions 0.6.1 and 0.6.2 have all the same Problem in the Screen of Minecraft

### ISSUE THREAD

**Issue by Titoo8899** [SmylerMC/terramap#13]
Hi,
it give a Problem on the top left of the Screen. I have your Mod and TerraMap 1 to 1 in my folder and a little bit other Decomods but in your newest Mod versions give it one big Bug what the Screen to 1/12 with a white square covered show the Picture. I hope you can fix it. Why so can I not play.
![2020-10-24_21 31 47](https://user-images.githubusercontent.com/42325138/97092062-f2abde80-1640-11eb-88fa-683e69e67501.png)

**Comment by SmylerMC** [comment]
Hello, this is an intended feature, it's a minimap. You can configure it (change it's size, disable it entirely, etc), in the Terramap's config. Terramap isn't really useful on a superflat world, it is supposed to be used on a Terra121 world. That's why your minimap is blue, it is centered onto the ocean at 0 0.

Here is an example image of the minimap in action on an Earth world (the minimap on the right is from an other mod (JourneyMap)):
![image](https://raw.githubusercontent.com/SmylerMC/terramap/master/images/minimap.png)
